// actionTypes.js

// Create Hunt
export const CREATE_HUNT_REQUEST = "CREATE_HUNT_REQUEST";
export const CREATE_HUNT_SUCCESS = "CREATE_HUNT_SUCCESS";
export const CREATE_HUNT_FAILURE = "CREATE_HUNT_FAILURE";

// Fetch Hunt
export const FETCH_HUNT_REQUEST = "FETCH_HUNT_REQUEST";
export const FETCH_HUNT_SUCCESS = "FETCH_HUNT_SUCCESS";
export const FETCH_HUNT_FAILURE = "FETCH_HUNT_FAILURE";

// Solve Clue
export const SOLVE_CLUE_REQUEST = "SOLVE_CLUE_REQUEST";
export const SOLVE_CLUE_SUCCESS = "SOLVE_CLUE_SUCCESS";
export const SOLVE_CLUE_FAILURE = "SOLVE_CLUE_FAILURE";

// Fetch Clue by ID
export const FETCH_CLUE_BY_ID_REQUEST = "FETCH_CLUE_BY_ID_REQUEST";
export const FETCH_CLUE_BY_ID_SUCCESS = "FETCH_CLUE_BY_ID_SUCCESS";
export const FETCH_CLUE_BY_ID_FAILURE = "FETCH_CLUE_BY_ID_FAILURE";

// Get All Hunts
export const GET_ALL_HUNTS_REQUEST = "GET_ALL_HUNTS_REQUEST";
export const GET_ALL_HUNTS_SUCCESS = "GET_ALL_HUNTS_SUCCESS";
export const GET_ALL_HUNTS_FAILURE = "GET_ALL_HUNTS_FAILURE";
